const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
$("#theme").onclick=()=>document.body.classList.toggle("dark");
const grid=[[1,2,1,0,1],[0,1,2,1,0],[1,0,1,2,1],[2,1,0,1,2],[1,1,2,0,1]];
const kernels={edge:[[1,0,-1],[1,0,-1],[1,0,-1]],horizontal:[[1,1,1],[0,0,0],[-1,-1,-1]],blur:[[1/9,1/9,1/9],[1/9,1/9,1/9],[1/9,1/9,1/9]],sharpen:[[0,-1,0],[-1,5,-1],[0,-1,0]]};
const mat=m=>'<div class="matrix">'+m.flat().map(x=>'<span>'+Number(x.toFixed?x.toFixed(2):x)+'</span>').join("")+'</div>';
function conv(m,k){return Array.from({length:m.length-2},(_,i)=>Array.from({length:m[0].length-2},(_,j)=>k.reduce((s,r,a)=>s+r.reduce((q,v,b)=>q+m[i+a][j+b]*v,0),0)))}
function renderConv(){const k=kernels[$("#kernel").value],o=conv(grid,k);$("#convLab").innerHTML='<b>Input</b>'+mat(grid)+'<b>Kernel</b>'+mat(k)+'<b>Feature map — click a value</b><div class="matrix">'+o.flat().map((x,i)=>'<span data-out="'+i+'" style="cursor:pointer">'+x.toFixed(2)+'</span>').join("")+'</div>';$$("[data-out]").forEach(b=>b.onclick=()=>{let i=+b.dataset.out,j=i%3,r=Math.floor(i/3),w=grid.slice(r,r+3).map(x=>x.slice(j,j+3)),p=w.flat().map((x,z)=>x*k.flat()[z]);$("#convCalc").innerHTML='<b>Trace output ['+r+','+j+']</b><br>Window '+mat(w)+'<br>Products: '+p.map(x=>x.toFixed(2)).join(" + ")+'<br><strong>Sum = '+o[r][j].toFixed(2)+'</strong>'})}
renderConv();$("#convRun").onclick=renderConv;
$("#reluLab").innerHTML=mat([[-2,1,4],[-1,0,3],[2,-3,5]])+'<br>↓ ReLU ↓'+mat([[0,1,4],[0,0,3],[2,0,5]]);
$("#poolLab").innerHTML=mat([[1,5,2,0],[3,4,7,1],[6,2,8,3],[0,1,4,9]])+'<br>↓ 2×2 max ↓'+mat([[5,7],[6,9]]);
const journey=[["IMAGE","Pixels are stored as H×W×C numbers."],["TENSOR","X∈R^(H×W×C): the image becomes a mathematical object."],["FEATURES","Convolution and nonlinear layers detect useful visual patterns."],["PATCHES","A ViT splits the image into fixed-size blocks."],["EMBEDDINGS","Each patch is flattened and linearly mapped into a vector."],["ATTENTION","Q,K,V determine which tokens exchange information."],["ALIGNMENT","Image and text representations are compared or projected."],["TOKENS","The language model predicts the next token from logits."],["LANGUAGE","Repeated conditional predictions form a sentence."]];
$("#journey").innerHTML=journey.map((x,i)=>'<button data-j="'+i+'">'+String(i+1).padStart(2,"0")+'<br>'+x[0]+'</button>').join("");
function journeyShow(i){$$("[data-j]").forEach(b=>b.classList.toggle("active",+b.dataset.j===i));$("#journeyDetail").innerHTML='<b>'+journey[i][0]+'</b><br>'+journey[i][1]}
$$("[data-j]").forEach(b=>b.onclick=()=>journeyShow(+b.dataset.j));journeyShow(0);
const levels={simple:"Imagine the image as a pile of numbers. Each stage transforms those numbers into a representation that preserves information useful for the next stage.",math:"The pipeline is a sequence of functions: X→f_visual(X)→Z_visual→P(Z_visual)→Z_language→softmax(logits). Every arrow changes a mathematical representation.",viva:"Be ready to explain not only what each block does, but why its dimensions are valid, what information it preserves, and what would fail if the block were removed."};
function level(k){$("#levelPanel").innerHTML='<b>'+k.toUpperCase()+'</b><p>'+levels[k]+'</p>'}$$(".level").forEach(b=>b.onclick=()=>{$$(".level").forEach(x=>x.classList.remove("active"));b.classList.add("active");level(b.dataset.level)});level("simple");
function patch(){let n=+$("#imgSize").value,p=+$("#patchSize").value,N=Math.floor(n/p),count=N*N;$("#patchGrid").style.gridTemplateColumns='repeat('+Math.min(N,14)+',1fr)';$("#patchGrid").innerHTML=Array.from({length:Math.min(count,196)},(_,i)=>'<button data-p="'+i+'"></button>').join("");$("#patchMath").innerHTML='N=(H/P)×(W/P) = '+N+'×'+N+' = <strong>'+count+' patches</strong><br>Each RGB patch contains P×P×3 = '+(p*p*3)+' values.';$$("[data-p]").forEach(b=>b.onclick=()=>{$$("[data-p]").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#patchMath").innerHTML='Selected patch '+(+b.dataset.p+1)+'<br>Shape: '+p+'×'+p+'×3<br>Flattened vector: '+(p*p*3)+' dimensions → embedding.'})}$("#imgSize").oninput=patch;$("#patchSize").oninput=patch;patch();
function heat(id,n=8){let a=Array.from({length:n*n},(_,i)=>.1+.9*((Math.sin(i*1.7)+1)/2));$(id).innerHTML=a.map(v=>'<i style="--v:'+v+'"></i>').join("")}heat("#peHeatmap");
$("#pePos").oninput=e=>$("#peReadout").textContent='position = '+e.target.value+' · PE₀≈'+Math.sin(+e.target.value).toFixed(3);
const scores=[[2.4,.3,1.1,.2],[.4,2.1,.7,.2],[1.2,.6,2.5,.5],[.2,.3,.8,2.2]],sm=a=>{let m=Math.max(...a),e=a.map(x=>Math.exp(x-m)),s=e.reduce((x,y)=>x+y,0);return e.map(x=>x/s)};
function renderAttn(){let weights=scores.map(r=>sm(r));$("#scoreMatrix").innerHTML=scores.flat().map((x,i)=>'<button data-a="'+i+'">'+x.toFixed(1)+'</button>').join("");$("#attnMatrix").innerHTML=weights.flat().map((x,i)=>'<button data-w="'+i+'">'+x.toFixed(2)+'</button>').join("");$("#dimTracker").innerHTML=["X · 4×4","Q=XWQ · 4×2","K=XWK · 4×2","QKᵀ · 4×4","softmax · 4×4","AV · 4×2"].map(x=>'<div>'+x+'</div>').join("");$$("[data-a]").forEach(b=>b.onclick=()=>{$$("[data-a]").forEach(x=>x.classList.remove("active"));b.classList.add("active");let i=+b.dataset.a,r=Math.floor(i/4),c=i%4;$("#attnCalc").innerHTML='<b>Query '+r+' → Key '+c+'</b><br>Score = '+scores[r][c]+'<br>Softmax weight = '+weights[r][c].toFixed(4)+'<br>This is how much query '+r+' attends to key '+c+'.'})}renderAttn();
function parse(s){return s.split(",").map(Number).filter(Number.isFinite)}$("#cosine").onclick=()=>{let a=parse($("#ivec").value),b=parse($("#tvec").value);if(a.length!==b.length||!a.length)return $("#cosResult").textContent="Use equal-length numeric vectors.";let d=a.reduce((s,x,i)=>s+x*b[i],0),na=Math.hypot(...a),nb=Math.hypot(...b);$("#cosResult").textContent='dot='+d.toFixed(3)+' · ||I||='+na.toFixed(3)+' · ||T||='+nb.toFixed(3)+' · cosine='+(d/(na*nb)).toFixed(4)};
$("#cosine").click();
const sim=[[.91,.18,.32],[.12,.86,.24],[.28,.21,.94]];function contrast(){let t=+$("#temperature").value,ex=sim.map(r=>{let e=r.map(x=>Math.exp(x/t)),s=e.reduce((a,b)=>a+b,0);return e.map(x=>x/s)});$("#contrastive").innerHTML='<span></span><span>dog</span><span>car</span><span>tree</span>'+ex.flatMap((r,i)=>['image '+(i+1),...r.map(x=>'<span>'+x.toFixed(2)+'</span>')]).join("");let loss=-ex.reduce((s,r,i)=>s+Math.log(r[i]),0)/3;$("#contrastLoss").textContent='Educational image→text cross-entropy loss = '+loss.toFixed(4)+' at τ='+t.toFixed(1)}$("#temperature").oninput=e=>{$("#tempReadout").textContent=e.target.value;contrast()};contrast();
const cross={dog:[.8,.2,.7,.1,.1,.2,.1,.1,.1,.1,.1,.1,.1,.1,.1,.1],red:[.1,.1,.1,.1,.1,.1,.1,.7,.6,.2,.1,.1,.1,.1,.1,.1],running:[.1,.1,.1,.1,.6,.8,.5,.2,.1,.1,.1,.1,.1,.1,.1,.1]};$("#imageMap").innerHTML=Array.from({length:16},(_,i)=>'<button data-patch="'+i+'">'+String(i+1).padStart(2,"0")+'</button>').join("");$("#crossTokens").innerHTML=Object.keys(cross).map(x=>'<button data-token="'+x+'">'+x+'</button>').join("");function crossShow(t){let v=cross[t];$$("[data-patch]").forEach((b,i)=>b.classList.toggle("hot",v[i]>.55));$("#crossDetail").innerHTML='<b>'+t+'</b> attends most strongly to patch '+(v.indexOf(Math.max(...v))+1)+' · weight '+Math.max(...v).toFixed(2)}$$("[data-token]").forEach(b=>b.onclick=()=>crossShow(b.dataset.token));crossShow("dog");
function softmax(a){let m=Math.max(...a),e=a.map(x=>Math.exp(x-m)),s=e.reduce((x,y)=>x+y,0);return e.map(x=>x/s)}$("#softmaxBtn").onclick=()=>{let p=softmax(parse($("#logits").value));$("#probs").innerHTML=p.map((x,i)=>'<div><small>token '+(i+1)+' · '+(x*100).toFixed(1)+'%</small><div style="height:12px;background:var(--soft);margin:4px 0 8px"><div style="height:100%;width:'+(x*100)+'%;background:var(--accent)"></div></div></div>').join("")};$("#softmaxBtn").click();
const sequence=["A","dog","is","running","."],genState=[];function renderGen(){$("#generationTrace").innerHTML=genState.length?genState.map((x,i)=>'<div>'+sequence.slice(0,i).join(" ")+' → <b>“'+x+'”</b></div>').join(""):'<div>IMAGE → <b>ready for first token</b></div>'}$("#generate").onclick=()=>{if(genState.length<sequence.length)genState.push(sequence[genState.length]);renderGen()};$("#resetGen").onclick=()=>{genState.length=0;renderGen()};renderGen();
function sandbox(op){let c=$("#sandboxCard");if(op==="multiply")c.innerHTML='<div class="grid two"><div><label>A<textarea id="A">1,2;3,4</textarea></label><label>B<textarea id="B">5,6;7,8</textarea></label><button id="runSB" class="btn primary">Multiply</button></div><div><h3>Result</h3><div id="sbOut" class="result"></div></div></div>';if(op==="softmax")c.innerHTML='<label>Vector<input id="sv" value="2,1,0"></label><button id="runSB" class="btn primary">Softmax</button><div id="sbOut" class="result"></div>';if(op==="cosine")c.innerHTML='<label>A<input id="sa" value="1,2,0"></label><label>B<input id="sb" value="1,1,1"></label><button id="runSB" class="btn primary">Cosine</button><div id="sbOut" class="result"></div>';if(op==="relu")c.innerHTML='<label>Values<input id="rv" value="-2,3,-1,5"></label><button id="runSB" class="btn primary">Apply ReLU</button><div id="sbOut" class="result"></div>';$("#runSB").onclick=()=>{let out=$("#sbOut");try{if(op==="multiply"){let A=$("#A").value.split(";").map(r=>parse(r)),B=$("#B").value.split(";").map(r=>parse(r));if(A[0].length!==B.length)throw Error("Inner dimensions do not match.");let C=A.map(r=>B[0].map((_,j)=>r.reduce((s,x,k)=>s+x*B[k][j],0)));out.innerHTML=mat(C)+'<br>'+A.length+'×'+A[0].length+' · '+B.length+'×'+B[0].length+' → '+C.length+'×'+C[0].length}else if(op==="softmax")out.textContent=softmax(parse($("#sv").value)).map(x=>x.toFixed(4)).join(", ");else if(op==="cosine"){let a=parse($("#sa").value),b=parse($("#sb").value),d=a.reduce((s,x,i)=>s+x*b[i],0);out.textContent=(d/(Math.hypot(...a)*Math.hypot(...b))).toFixed(4)}else out.textContent=parse($("#rv").value).map(x=>Math.max(0,x)).join(", ")}catch(e){out.textContent=e.message}}}$$(".tab").forEach(b=>b.onclick=()=>{$$(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");sandbox(b.dataset.op)});sandbox("multiply");
const qs={easy:[["What is convolution?","A local weighted sum: the kernel combines nearby pixels to produce a feature value.","State the convolution equation and explain locality."],["Why use ReLU?","ReLU(x)=max(0,x), adding non-linearity while keeping positive activations.","What would a network of only linear layers become?"],["What is an image patch?","A fixed spatial block of pixels used as one token by a Vision Transformer.","For 224×224 with 16×16 patches, how many patches?"]],medium:[["Why divide by √dₖ?","Without scaling, dot products can grow with dimension and softmax can saturate.","What does saturation do to gradients?"],["Why add positional information?","Self-attention alone does not inherently encode the original spatial order of a token sequence.","How does sinusoidal encoding represent position?"],["What does cosine similarity measure?","The normalized dot product, so it compares the angle between vectors rather than their raw magnitude.","What does cosine≈1 suggest?"]],hard:[["Why is QKᵀ an N×N matrix?","There are N queries and N keys; every query is compared with every key.","What is the computational consequence as N grows?"],["Explain a vision-language projector mathematically.","It maps visual token dimension d_v to a dimension compatible with the language model, e.g. Z_vW_P+b.","Why can't arbitrary dimensions simply be added?"],["Explain autoregressive factorization.","P(y₁…y_T|X)=∏ₜP(yₜ|y_<t,X): the joint sequence probability factors into conditional next-token probabilities.","Why must the previous generated tokens be included?"]]};let qi=0;function viva(){let d=$("#difficulty").value,a=qs[d],q=a[qi%a.length];$("#qNum").textContent='Question '+((qi%a.length)+1)+' / '+a.length;$("#question").textContent=q[0];$("#vivaHint").textContent='Hint: '+q[2];$("#answer").textContent=q[1];$("#vivaHint").hidden=true;$("#answer").hidden=true;$("#difficultyBar").style.width=d==="easy"?"30%":d==="medium"?"60%":"90%"}$("#difficulty").onchange=()=>{qi=0;viva()};$("#hintBtn").onclick=()=>$("#vivaHint").hidden=!$("#vivaHint").hidden;$("#showAnswer").onclick=()=>$("#answer").hidden=!$("#answer").hidden;$("#nextQ").onclick=()=>{qi++;viva()};viva();
$("#upload").onchange=e=>{let f=e.target.files[0];if(!f)return;let im=new Image;im.onload=()=>{let c=$("#imgCanvas"),ctx=c.getContext("2d"),s=Math.min(c.width/im.width,c.height/im.height),w=im.width*s,h=im.height*s;ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(im,0,0,w,h);$("#imgDim").textContent=im.height+" × "+im.width+" × 3";$("#pixelInfo").textContent="Image loaded. Click a pixel."};im.src=URL.createObjectURL(f)};$("#imgCanvas").onclick=e=>{let c=e.currentTarget,r=c.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)*c.width/r.width),y=Math.floor((e.clientY-r.top)*c.height/r.height),p=c.getContext("2d").getImageData(x,y,1,1).data;$("#pixelInfo").textContent='pixel ('+x+', '+y+') → RGB ('+p[0]+', '+p[1]+', '+p[2]+') → normalized ('+(p[0]/255).toFixed(3)+', '+(p[1]/255).toFixed(3)+', '+(p[2]/255).toFixed(3)+')'};
