const $=s=>document.querySelector(s);
$("#theme").onclick=()=>document.body.classList.toggle("dark");
const defaultGrid=[[1,2,1,0,1],[0,1,2,1,0],[1,0,1,2,1],[2,1,0,1,2],[1,1,2,0,1]];
const kernels={edge:[[1,0,-1],[1,0,-1],[1,0,-1]],horizontal:[[1,1,1],[0,0,0],[-1,-1,-1]],blur:[[1/9,1/9,1/9],[1/9,1/9,1/9],[1/9,1/9,1/9]],sharpen:[[0,-1,0],[-1,5,-1],[0,-1,0]]};
function matHTML(m){return '<div class="matrix">'+m.flat().map(x=>'<span>'+Number(x.toFixed?x.toFixed(2):x)+'</span>').join('')+'</div>'}
function conv(m,k){let o=[];for(let i=0;i<=m.length-3;i++){let r=[];for(let j=0;j<=m[0].length-3;j++){let s=0;for(let a=0;a<3;a++)for(let b=0;b<3;b++)s+=m[i+a][j+b]*k[a][b];r.push(s)}o.push(r)}return o}
function renderConv(){let k=kernels[$("#kernel").value],o=conv(defaultGrid,k);$("#convVisual").innerHTML='<div style="display:grid;grid-template-columns:1fr 1fr;gap:14px"><div><small>INPUT</small>'+matHTML(defaultGrid)+'</div><div><small>FEATURE MAP</small>'+matHTML(o)+'</div></div><p>Kernel:</p>'+matHTML(k)}
renderConv();$("#convRun").onclick=renderConv;
const cnn=conv(defaultGrid,kernels.edge);$("#cnnNumerical").innerHTML='<small>CONVOLUTION OUTPUT</small>'+matHTML(cnn)+'<p>After ReLU:</p>'+matHTML(cnn.map(r=>r.map(x=>Math.max(0,x))));
function heat(id,n=8){let a=Array.from({length:n*n},()=>Math.random());let max=Math.max(...a);$(id).innerHTML=a.map(x=>'<i style="--v:'+(.12+.88*x/max)+'"></i>').join('')}
heat("#peHeatmap");heat("#scoreMatrix",4);heat("#attnMatrix",4);heat("#crossHeatmap");
function simGrid(){let vals=[[.91,.18,.32],[.12,.86,.24],[.28,.21,.94]];$("#contrastive").innerHTML='<span></span><span>dog</span><span>car</span><span>tree</span>'+vals.flatMap((r,i)=>['image '+(i+1),...r.map(x=>'<span>'+x.toFixed(2)+'</span>')]).join('')}
simGrid();
$("#upload").onchange=e=>{let f=e.target.files[0];if(!f)return;let im=new Image;im.onload=()=>{let c=$("#imgCanvas"),ctx=c.getContext("2d");let scale=Math.min(c.width/im.width,c.height/im.height);let w=im.width*scale,h=im.height*scale;c.width=420;c.height=280;ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(im,0,0,w,h);$("#imgDim").textContent=im.height+" × "+im.width+" × 3";$("#pixelInfo").textContent="Image loaded. Click a pixel to inspect RGB values.";};im.src=URL.createObjectURL(f)};
$("#imgCanvas").onclick=e=>{let c=e.currentTarget,ctx=c.getContext("2d"),r=c.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)*c.width/r.width),y=Math.floor((e.clientY-r.top)*c.height/r.height),p=ctx.getImageData(x,y,1,1).data;$("#pixelInfo").textContent='pixel ('+x+', '+y+') → RGB ('+p[0]+', '+p[1]+', '+p[2]+') → normalized ('+(p[0]/255).toFixed(3)+', '+(p[1]/255).toFixed(3)+', '+(p[2]/255).toFixed(3)+')'};
function parseVec(s){return s.split(",").map(Number)}$("#cosine").onclick=()=>{let a=parseVec($("#ivec").value),b=parseVec($("#tvec").value),dot=a.reduce((s,x,i)=>s+x*b[i],0),na=Math.hypot(...a),nb=Math.hypot(...b);$("#cosResult").textContent='cos(I,T) = '+(dot/(na*nb)).toFixed(4)};
function softmax(a){let m=Math.max(...a),e=a.map(x=>Math.exp(x-m)),s=e.reduce((a,b)=>a+b,0);return e.map(x=>x/s)}$("#softmaxBtn").onclick=()=>{let p=softmax(parseVec($("#logits").value));$("#probs").innerHTML=p.map((x,i)=>'<div style="margin:7px 0"><small>token '+(i+1)+' · '+(x*100).toFixed(1)+'%</small><div style="height:12px;background:var(--soft);border-radius:3px"><div style="width:'+(x*100)+'%;height:100%;background:var(--accent);border-radius:3px"></div></div></div>').join('')};
$("#multiply").onclick=()=>{let A=$("#matA").value.split(";").map(r=>r.split(",").map(Number)),B=$("#matB").value.split(";").map(r=>r.split(",").map(Number));if(A[0].length!==B.length){$("#matResult").textContent="Inner dimensions must match.";return}let C=A.map(r=>B[0].map((_,j)=>r.reduce((s,x,k)=>s+x*B[k][j],0)));$("#matResult").innerHTML=matHTML(C);$("#matDims").textContent=A.length+"×"+A[0].length+" · "+B.length+"×"+B[0].length+" → "+C.length+"×"+C[0].length};
const qs=[["What is convolution?","A local weighted sum. A small kernel slides over an input and computes Y(i,j)=ΣΣX(i+m,j+n)K(m,n)."],["Why is ReLU used?","ReLU(x)=max(0,x). It introduces non-linearity while keeping positive activations and gives a simple gradient."],["Why divide attention scores by √dₖ?","The dot-product variance grows with the key dimension. Scaling keeps softmax from becoming unnecessarily saturated."],["What is an image patch?","A small spatial block of pixels extracted from the image. ViT flattens each patch and maps it to an embedding."],["What is an embedding?","A learned vector representation. A patch or token is mapped to a point in a d-dimensional representation space."],["What does QKᵀ represent?","Pairwise compatibility scores: each query is compared with every key."],["What does softmax do in attention?","It converts scores into non-negative weights that sum to one for each query."],["What is cosine similarity?","The normalized dot product. It measures angular similarity between two vectors."],["What does a projector do in a VLM?","It transforms visual features into a representation space compatible with the language model."],["What is a logit?","An unnormalized score produced before softmax. Higher relative logits generally produce higher probabilities."],["What is autoregressive generation?","Predicting one token at a time conditioned on the image and all previously generated tokens."],["What is cross-modal attention?","Attention where queries from one modality, such as text, attend to keys and values from another modality, such as image tokens."]];
let qi=0;function viva(){let q=qs[qi];$("#qNum").textContent="Question "+(qi+1)+" / "+qs.length;$("#question").textContent=q[0];$("#answer").textContent=q[1];$("#answer").hidden=true}viva();$("#showAnswer").onclick=()=>$("#answer").hidden=!$("#answer").hidden;$("#nextQ").onclick=()=>{qi=(qi+1)%qs.length;viva()};
$("#multiply").click();$("#softmaxBtn").click();$("#cosine").click();